metadata:
  name: oam-ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  rules:
  - host: iinfo1.infobelt.net
    http:
      paths:
      - path: /
        backend:
          service:
            port:
              number: 80
            name: oam-ui
        pathType: Prefix
  - host: drill.iinfo1.infobelt.net
    http:
      paths:
      - path: /
        backend:
          service:
            port:
              number: 8047
            name: oam-drill-service
        pathType: Prefix
  tls:
  - secretName: iinfo1-infobelt-net
    hosts:
    - iinfo1.infobelt.net
  - secretName: drill-iinfo1-infobelt-net
    hosts:
    - drill.iinfo1.infobelt.net
