---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-onboard-pv-dev
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b3e272f85fe67e03::fsap-0dd090a5ebba3a7e8  # oam-onboarding fsap to added
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-onboard-dev
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: efs-onboard-pv-dev
  resources:
    requests:
      storage: 1Mi
---
