---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-oam-pv-dev-2
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0b3e272f85fe67e03::fsap-090bd958e02c1ea5c  # updated fsap to oam-dev-02 ## fs accesspoint has to be created for each env/customer and update here
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-oam-dev-2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: efs-oam-pv-dev-2
  resources:
    requests:
      storage: 1Mi
---
